### ISSUE TITLE
relative paths issue?

### ISSUE THREAD

**Issue by PPRIESTER-KMBS** [Bases-Dev-Tools/bases.cli-Example#3]
Hi! I followed the steps to install. got the sdk, .net 8, then installed the cli. I created sample json files and they won't run any installer, verified the json formatting is valid, it doesn't even run a simple .msi grabbed from the web. I redirected the bases install command to write to a text file and got the following: 

Unhandled exception. System.IO.IOException: The handle is invalid.
   at System.ConsolePal.GetBufferInfo(Boolean throwOnNoConsole, Boolean& succeeded)
   at System.ConsolePal.Clear()
   at Program.Main(String[] args) in C:\Users\jacob\bases-tech\bases.cli\Program.cs:line 9

C:\Users\jacob\bases-tech\bases.cli\Program.cs:line 9 - so is there something we noobs can do to remove references to this dev environment - make paths relative, or is there another published version I'm missing? Thanks

**Comment by BasesJs** [comment]
Looking into it - Sorry, I had my notifications off for this org apparently and just saw this.

**Comment by BasesJs** [comment]
Interestingly, that line of code is a "Console.Clear", but I managed to traced the issue to this vscode issue [#2336](https://github.com/dotnet/vscode-csharp/issues/2336).

I checked the main repo and sure enough, the .gitignore was not ignoring the configured folders the the .vscode folder was committed to the repo - it's where that non-relative path was coming from. I have a newly packaged version of the CLI that is not published to nuget just yet, pending testing. 

I tested the original on 3 different VM's, 2 different PC's - so I'm not sure what might have happened, but if you're interested in testing this fix pre-publish I can provide the packaged file and a quick script to install it, otherwise I'll be testing on my 3 vm's and 2 pc's as I did last time, then publish the update.

**Comment by PPRIESTER-KMBS** [comment]
Ha, awesome! Thanks for looking into this. I'm open to testing this out myself as well, just let me know!

Sincerely,

[https://kmbscontent.konicaminolta.us/signature/km_winter_logo.gif]
Phillip Priester

IIM Solutions Engineer II

Visit us: Count on Konica Minolta<https://kmbs.konicaminolta.us/>
________________________________

**Comment by BasesJs** [comment]
Phillip - there's a new branch of the example project for issue3. It's got a script to install the test build. 
![image](https://github.com/user-attachments/assets/292a9e44-c818-44f3-bf7e-36b1b3dc480d)

Try running pulling that branch and running that script, see if the errors are still present. I will do some further testing as well, I'll spin up a new vm tomorrow and see if I have an issues.
